name: Run Selenium Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version (e.g., 3.8, 3.9, etc.)

    - name: Install dependencies
      run: |
        pip install selenium webdriver-manager

    - name: Check installed packages
      run: pip list  # This will confirm if selenium is installed

    - name: Run Selenium test
      run: python Google.py
