name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if npm install; then
             "Dependencies installed successfully!"
          else
             "Failed to install dependencies. Exiting..."
          

      - name: Install Mocha Globally (if Mocha is not in `package.json`)
        run: |
          if npm install -g mocha; then
             "Mocha installed successfully!"
          else
             "Failed to install Mocha. Exiting..."
          
      - name: Run Mocha Tests
        run: |
          if mocha; then
             "Mocha tests passed successfully!"
          else
             "Mocha test execution failed. Exiting..."
           

      - name: Build npm Packages
        run: |
          if npm run build; then
             "npm packages built successfully!"
          else
             "Failed to build npm packages. Exiting..."
           

      - name: Run npm Tests
        run: |
          if npm test; then
             "npm tests passed successfully!"
          else
             "npm tests failed. Exiting..."
         

      - name: Check Docker Version
        run: |
          if docker --version; then
             "Docker is installed."
          else
             "Docker is not installed or the version is incompatible. Exiting..."
        

      - name: Build Docker Image
        run: |
          if docker build -t my-selenium-app:latest .; then
             "Docker image built successfully!"
          else
             "Docker image build failed. Exiting..."
         

      - name: Save Docker Image
        run: |
          if docker image save my-selenium-app:latest | xz -z -e -7 -T0 > image.xz; then
             "Docker image saved successfully!"
          else
             "Failed to save Docker image. Exiting..."
        

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_id }}  # Use the run id as the version tag
          release_name: Release ${{ github.run_id }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically available in Actions

      - name: Upload Release Asset
        run: |
          if [[ -n "${{ steps.create_release.outputs.upload_url }}" ]]; then
             "Uploading release asset..."
            actions/upload-release-asset@v1
          else
             "Upload URL not found. Exiting..."
        

      - name: Install Selenium
        run: |
          if pip install selenium; then
             "Selenium installed successfully!"
          else
             "Failed to install Selenium. Exiting..."
          

      - name: Install Python dependencies
        run: |
          if python -m pip install --upgrade pip && pip install selenium webdriver-manager; then
             "Python dependencies installed successfully!"
          else
             "Failed to install Python dependencies. Exiting..."
       

      - name: Run Google Search Test
        id: run_tests
        run: |
          if python Google.py > test_results.log; then
             "Tests executed successfully!"
          else
             "There were errors in the tests. Check the logs below:"
            cat test_results.log
        

      - name: Show test results
        run: |
          if [[ -f test_results.log ]]; then
            cat test_results.log
          else
             "Test results log not found."
        
      
      - name: Confirm test execution
        if: ${{ steps.run_tests.outcome == 'success' }}
        run: |
           "All tests executed successfully!"
            cat test_results.log
      
      - name: Handle test failure
        if: ${{ steps.run_tests.outcome != 'success' }}
        run: |
          "Test failures detected. Review the logs."
          cat test_results.log

      - name: Deploy application
        run: |
          if npm run deploy; then
          "Application deployed successfully!"
          else Failed to deploy application. Exiting..."
         
